version: '3.8'
services:
  mariadb:
    networks:
      - ci
    environment:
        MARIADB_ROOT_PASSWORD: "rootpassword"
        MARIADB_DATABASE: "laravel_testing"
        MARIADB_USER: "mysqluser"
        MARIADB_PASSWORD: "mysqlpassword"

  php:
    networks:
      - ci
    volumes:
      - .:/var/www/html/
    working_dir: /var/www/html/
    environment:
      AUTORUN_ENABLED: false
    depends_on:
      - mariadb

  node:
    image: node:18
    volumes:
      - .:/usr/src/app/
    working_dir: /usr/src/app/
    networks: 
      - ci

  mailpit:
    image: axllent/mailpit
    networks:
      - ci
    depends_on:
      - traefik

networks:
  ci: