version: '3.8'
services:

  traefik:
      networks:
          - web-public
      ports:
        - "80:80"
        - "443:443"
      deploy:
        update_config:
          parallelism: 1
          delay: 5s
          order: stop-first
        placement:
          constraints:
            # Make the traefik service run only on the node with this label
            # as the node with it has the volume for the certificates
            - node.role==manager
      volumes:
        # Add Docker as a mounted volume, so that Traefik can read the labels of other services
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - certificates:/certificates
      configs:
        - source: traefik
          target: /etc/traefik/traefik.yml

  mariadb:
    networks:
      - web-public
    environment:
        MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
        MARIADB_DATABASE: "${DB_NAME}"
        MARIADB_USER: "${DB_USERNAME}"
        MARIADB_PASSWORD: "${DB_PASSWORD}"
    deploy:
      placement:
        constraints:
          # Make the MySQL service run only on the node with this label
          # as the node with it has the volume for the database
          - node.role==manager
    volumes:
      - database_data:/var/lib/mysql
      - database_custom_conf:/etc/mysql/conf.d
      - database_shared:/shared

  #### Uncomment and change keys and IP addresses below if you want to use an SSH
  #### tunnel to access the database from your local machine
  # ssh:
  #   image: serversideup/docker-ssh
  #   ports:
  #     - target: 2222
  #       published: 2222
  #       mode: host
  #   environment:
  #     AUTHORIZED_KEYS: >
  #       "# Start Keys
  #        ssh-ed25519 1234567890abcdefghijklmnoqrstuvwxyz user-a
  #        ssh-ed25519 abcdefghijklmnoqrstuvwxyz1234567890 user-b
  #        # End Keys")
  #     ALLOWED_IPS: "AllowUsers *@127.0.0.1"
  #   volumes:
  #     - tunnel_ssh_host_keys:/etc/ssh/ssh_host_keys
  #   networks:
  #       - web-public

  php:
    image: example.com/myrepo/my-laravel-app:latest
    networks:
      - web-public
    volumes:
      - "storage_private:/var/www/html/storage/app/private/"
      - "storage_public:/var/www/html/storage/app/public/"
      - "storage_sessions:/var/www/html/storage/framework/sessions"
      - "storage_logs:/var/www/html/storage/logs"
    environment:
      PHP_POOL_NAME: "my-laravel-app"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
      labels:
        # Accept traffic for HTTP
        - "traefik.enable=true"
        - "traefik.http.routers.my-laravel-app-http.rule=HostRegexp(`laravel.dev.test`)"
        - "traefik.http.routers.my-laravel-app-http.entrypoints=web"
        - "traefik.http.routers.my-laravel-app-http.service=my-laravel-app-http"
        - "traefik.http.services.my-laravel-app-http.loadbalancer.server.port=80"
        - "traefik.http.services.my-laravel-app-http.loadbalancer.server.scheme=http"
        # Accept traffic for HTTPS
        - "traefik.http.routers.my-laravel-app-https.rule=HostRegexp(`laravel.dev.test`)"
        - "traefik.http.routers.my-laravel-app-https.entrypoints=websecure"
        - "traefik.http.routers.my-laravel-app-https.service=my-laravel-app-https"
        - "traefik.http.routers.my-laravel-app-https.tls=true"
        - "traefik.http.services.my-laravel-app-https.loadbalancer.server.port=443"
        - "traefik.http.services.my-laravel-app-https.loadbalancer.server.scheme=https"

configs:
  traefik:
    name: "traefik.yml"
    file: ./.infrastructure/conf/traefik/prod/traefik.yml

volumes:
  certificates:
  database_data:
  database_custom_conf:
  database_shared:
  storage_private:
  storage_public:
  storage_sessions:
  storage_logs:
  tunnel_ssh_host_keys:

networks:
  web-public:
